### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Soda-City-PoGo** [0x736a64/Muggle_Contraption#1]
`soda@soda-vps:~/muggle$ node bot.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './private/auth.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/soda/muggle/bot.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)`

**Comment by 0x736a64** [comment]
Updated instructions that should resolve this issue. Please check updated readme. Also refactored config setup. Let me know any more issues, this is a new project.

**Comment by Soda-City-PoGo** [comment]
yep that at least got it running for me thx, its still throwing a few errors but i got it running with pm2 using the watch/reload flag for when it crashes thx for all your work on this!

**Comment by Soda-City-PoGo** [comment]
> soda@soda-vps:~/muggle$ node bot.js
Logged in as Aparecium#9529 - Aparecium!
/home/soda/muggle/modules/controllers/role.js:70
    let profession = msg.guild.roles.find(role => role.name.toLowerCase() === professionName.toLowerCase());
                                                                                             ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at msg.guild.roles.find.role (/home/soda/muggle/modules/controllers/role.js:70:94)
    at Map.find (/home/soda/muggle/node_modules/discord.js/src/util/Collection.js:506:11)
    at Object.addProfession [as callback] (/home/soda/muggle/modules/controllers/role.js:70:38)
    at listen (/home/soda/muggle/modules/controllers/command.js:46:23)
    at config.prefixes.forEach.prefix (/home/soda/muggle/bot.js:18:43)
    at Array.forEach (<anonymous>)
    at Client.bot.on.msg (/home/soda/muggle/bot.js:17:21)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/home/soda/muggle/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/soda/muggle/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)

>

**Comment by 0x736a64** [comment]
I think this has to do with creating roles in the discord server, which I have not documented yet. I will add this to the readme. Can you try adding corresponding roles that the bot will be using to your server?Here's a list that may help. Also, positioning of the roles is important, as the bot must be above the roles it is assigning.

**Comment by 0x736a64** [comment]
Houses:
- Gryffindor
- Slytherin
- Hufflepuff
- Ravenclaw

Municipalities:
- add these as you add them to config.json per README.md instructions
Professions:
- Auror
- Magizoologist
- Professor
